/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation ("org.junit.jupiter:junit-jupiter:5.12.+")          // 5.12.+ https://junit.org/junit5/
    implementation ("org.mockito:mockito-core:+")                 // 5.16.+ https://site.mockito.org/
    implementation ("com.google.truth:truth:+")                   // 1.4.4  https://truth.dev/
    implementation ("edu.cnu.cs:gooey:1.0.11.05")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher") // 1.12.+
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}